---
title: Análisis de datos de COVID-19 de Corta Rica mediante funciones del código base
  de R
author: "Mariano Arroyo"
date: '2022-05-11'
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
        
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentación
Este documento presenta gráficos generados a partir de los datos de COVID-19 en Costa Rica compartidos por el Ministerio de Salud en [https://geovision.uned.ac.cr/oges/](https://geovision.uned.ac.cr/oges/)

## Entradas

```{r carga-datos}
covid <- read.csv(file = "05_10_22_CSV_GENERAL.csv", sep = ";")
```


## Procesamiento

### Curación de datos

```{r conversion-fecha}
covid$FECHA <- as.Date(covid$FECHA, format = "%d/%m/%Y")
```

## Opciones generales

```{r opciones-generales}
options(scipen = 7)
```


## Salidas

### Gráficos

#### Casos acumulados

##### Positivos

```{r casos-positivos-acumulados}
plot(
  covid$FECHA,
  covid$positivos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos positivos acumulados de COVID en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos positivos"
)

# Formato del eje x
axis(side = 1,
     covid$FECHA,
     tick =FALSE,
     format(covid$FECHA,"%m-%y"),
     cex.axis = 0.7    
)

# Formato del eje y
axis(side = 2,
     covid$positivos,
     labels =TRUE,
     at = seq(0, 10000000, by = 200000),
     cex.axis = 0.7    
)
```

##### Fallecidos

```{r casos-fallecidos-acumulados}
plot(
  covid$FECHA,
  covid$fallecidos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Número de muertes de personas fallecidas por COVID-19 en Costa Rica",
  xlab = "Fecha",
  ylab = "Cantidad"
)

# Formato del eje x
axis(side = 1,
     covid$FECHA,
     tick =FALSE,
     format(covid$FECHA,"%m-%y"),
     cex.axis = 0.7    
)

# Formato del eje y
axis(side = 2,
     covid$fallecidos,
     labels =TRUE,
     at = seq(0, 10000, by = 2000),
     cex.axis = 0.7    
)
```